Benchmark tool for DIFI Source block
microsoft/azure-software-radio pull request #75
Opened 2022-04-21 03:19 UTC by 777arc

Currently the output is a plot of % packets received over sample rate (see example in ADO) which seemed more useful than just a single number

2022-04-25 22:04 UTC, jo-rivera requested changes

2022-04-25 22:04 UTC, jo-rivera commented on gr-azure-software-radio/utils/benchmark_difi_source.py
> +                sock_tx.send(msg)
should we consider using iperf to leverage other metrics as well? https://iperf3-python.readthedocs.io/en/latest/examples.html

2022-04-25 22:17 UTC, jo-rivera requested changes

2022-04-25 22:17 UTC, jo-rivera commented on gr-azure-software-radio/utils/benchmark_difi_source.py
> +                sock_tx.send(msg)
never mind... we are testing in loopback. It makes sense when we have the client and server in different machines, and we are sending traffic over the network

2022-04-25 22:21 UTC, jo-rivera commented
can we include instructions on how to run the benchmark test? does the user just run the flowgraph? what environment was used to run the test and generate the attached plot? (VM?)

2022-04-26 05:56 UTC, 777arc commented on gr-azure-software-radio/utils/benchmark_difi_source.py
> +# Generate and save a bunch of DIFI packets, we start the flowgraph then start recv()'ing
Rather keep it all in 1 file for convenience since it's a utility

2022-04-26 05:57 UTC, 777arc commented
> can we include instructions on how to run the benchmark test? does the user just run the flowgraph? what environment was used to run the test and generate the attached plot? (VM?)

I'll stick the details in the png itself

2022-04-28 02:14 UTC, jo-rivera approved these changes

2022-04-28 02:15 UTC, merged